-- noinspection SqlNoDataSourceInspectionForFile
CREATE ROLE read_only;
CREATE USER notry WITH PASSWORD 'BolshoiRozhok24123!&_' IN ROLE read_only;
CREATE DATABASE notrybro OWNER notry;

CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    SURNAME VARCHAR (50),
    PHONE VARCHAR (50),
    EMAIL VARCHAR (50),
    LOGIN VARCHAR (50) NOT NULL,
    LOGO VARCHAR (50),
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_USER_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE IF NOT EXISTS FILES
(
    ID        VARCHAR(255) NOT NULL PRIMARY KEY,
    DIRECTORY  VARCHAR(255) NOT NULL,
    FORMAT     VARCHAR(255) NOT NULL,
    URL        VARCHAR(255) NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITY (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    DESCRIPTION VARCHAR (255) NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_AUTHORITY_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITY (
  ID VARCHAR (100) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR (100) NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  AUTHORITY_ID VARCHAR (100) NOT NULL REFERENCES AUTHORITY (ID) ON DELETE CASCADE,
  VERSION BIGINT DEFAULT 1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODULES (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    NUMBER INTEGER NOT NULL,
    STATUS BOOLEAN NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LESSONS (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    URL VARCHAR (255),
    WATCHED BOOLEAN NOT NULL,
    NUMBER INTEGER NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODULE_LESSONS
(
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    MODULE_ID VARCHAR (100) NOT NULL REFERENCES MODULES (ID) ON DELETE CASCADE,
    LESSON_ID VARCHAR (100) NOT NULL REFERENCES LESSONS (ID) ON DELETE CASCADE,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FILE_LESSON
(
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    FILE_ID VARCHAR (100) NOT NULL REFERENCES FILES (ID) ON DELETE CASCADE,
    LESSON_ID VARCHAR (100) NOT NULL REFERENCES LESSONS (ID) ON DELETE CASCADE,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FILE_MODULE
(
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    FILE_ID VARCHAR (100) NOT NULL REFERENCES FILES (ID) ON DELETE CASCADE,
    MODULE_ID VARCHAR (100) NOT NULL REFERENCES MODULES (ID) ON DELETE CASCADE,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USER_LESSON (
    ID VARCHAR (100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR (100) NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
    LESSON_ID VARCHAR (100) NOT NULL REFERENCES LESSONS (ID) ON DELETE CASCADE,
    WATCHED BOOLEAN NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

GRANT SELECT, INSERT, UPDATE, DELETE ON
    users, user_authority, modules, module_lessons, lessons, file_lesson, file_module, files, authority TO read_only;


